language: c
dist: bionic,
git:
  submodules: false
branches:
  only:
  - master
before_install:
- chmod +x ./install.sh
script:
- ./install.sh
notifications:
  email:
    recipients:
    - sharry.r.xu@gmail.com
    on_success: change
    on_failure: always
