export NVM_DIR="$HOME/.nvm"
export CUSTOM_BIN="$HOME"/.bin
export PACKAGE_BIN=/usr/local/bin
export PACKAGE_SBIN=/usr/local/bin/sbin
export LLVM_PATH=/usr/local/opt/llvm/bin
export PYENV_ROOT="$HOME/.pyenv"
export PYENV_BIN="$PYENV_ROOT/bin"
export PYTHON_CONFIGURE_OPTS="--enable-framework"
export PATH=$CUSTOM_BIN:$PYENV_BIN:$PACKAGE_BIN:$PACKAGE_SBIN:$LLVM_PATH:$PATH:$NVM_DIR

export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export HOMEBREW_NO_AUTO_UPDATE=true

export UPDATE_ZSH_DAYS=1
export LANG=en_US.UTF-8
export EDITOR='nvim'
export SSH_KEY_PATH="~/.ssh/rsa_id"
export TERM='screen-256color'

export DOTFILES_PATH="$HOME"/Desktop/Projects/dotfiles
