#!/usr/bin/env zsh

source "$HOME"/.profile

# over-write some arguments.
export GOPATH=$HOME/go
export PACKAGE_BIN=/usr/local/bin
export PACKAGE_SBIN=/usr/local/sbin

export PATH=$PACKAGE_BIN:$PACKAGE_SBIN:$PATH
