#!/usr/bin/env zsh

system_name=$(uname -s)

function load-python() {
  if which pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
  fi
}

function load-nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
}

function load-travis() {
  [ -f "$HOME"/.travis/travis.sh ] && source "$HOME"/.travis/travis.sh
}

function load-fzf() {
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}

alias mongod2='/usr/local/Cellar/mongodb@2.6/2.6.12/bin/mongod'
alias emacs-term='emacs -nw'
alias vim='emacsclient'
if [ -z "$INSIDE_EMACS" ]; then
	start-or-restart-emacs
fi

export ZSH=$HOME/.oh-my-zsh

# Do not enable auto-correct.
unsetopt correct_all

# set -o vi

ZSH_THEME="sharry"
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="false"
#HIST_STAMPS="mm/dd/yyyy"
HISTSIZE=1000
SAVEHIST=1000
#ZSH_THEME_GIT_PROMPT_CACHE="false"

plugins=(
  git-prompt
  tmux
  zsh-syntax-highlighting
  zsh-autosuggestions
  zsh-completions
  autojump
  osx
  emoji
)

# When not in emacs's terminal, automatically startup tmux.
# Only when emacs is totally startup, this variable is set.
if [ -z "$INSIDE_EMACS" ]; then
  ZSH_TMUX_AUTOSTART=true
  ZSH_TMUX_AUTOQUIT=false
else
  ZSH_TMUX_AUTOSTART=false
  ZSH_TMUX_AUTOQUIT=false
fi

source $ZSH/oh-my-zsh.sh

load-python
load-nvm
