#!/usr/bin/env zsh

system_name=$(uname -s)

function load-python() {
  if command-exist pyenv; then
    eval "$(pyenv init -)"
    pyenv shell 2.7.14
  fi
}

function load-nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvm use default 1>/dev/null 2>&1
}

function load-travis() {
  [ -f "$HOME"/.travis/travis.sh ] && source "$HOME"/.travis/travis.sh
}

function load-fzf() {
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}

if [[ $system_name == 'Darwin' ]]; then
  # Config homebrew
  export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
  export HOMEBREW_NO_AUTO_UPDATE=true

  alias mongod2='/usr/local/Cellar/mongodb@2.6/2.6.12/bin/mongod'
  alias emacs-term='emacs -nw'
  alias vim='nvim'

elif [[ $system_name == 'Linux' ]]; then

  alias mongod='mongod'
  alias emacs='emacs'
  alias vim='nvim'
fi

export ZSH=$HOME/.oh-my-zsh

# Do not enable auto-correct.
unsetopt correct_all

# set -o vi

ZSH_THEME="sharry"
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="false"
# HIST_STAMPS="mm/dd/yyyy"
HISTSIZE=1000
SAVEHIST=1000
ZSH_THEME_GIT_PROMPT_CACHE="false"

plugins=(
  git
  git-prompt
  tmux
  zsh-syntax-highlighting
  #  zsh-autosuggestions
  zsh-completions
  autojump
)

# When not in emacs's terminal, automatically startup tmux.
if [ -z "$INSIDE_EMACS" ]; then
  ZSH_TMUX_AUTOSTART=false
  ZSH_TMUX_AUTOQUIT=false
  load-nvm
else
  ZSH_TMUX_AUTOSTART=false
fi

source $ZSH/oh-my-zsh.sh

load-python
