#!/bin/bash

function load-python() {
  if which pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
  fi
}

function load-nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvm use default 1>/dev/null 2>&1
}

function load-travis() {
  [ -f "$HOME"/.travis/travis.sh ] && source "$HOME"/.travis/travis.sh
}

function load-fzf() {
  [ -f ~/.fzf.bash ] && source "$HOME"/.fzf.bash
}

load-python
load-nvm

alias emacs-term='emacs -nw'
alias vim='emacsclient'

source "$HOME"/.profile
source "$HOME/.bashrc"
