#!/bin/bash

function load-python() {
  if command-exist pyenv; then
    eval "$(pyenv init -)"
    pyenv shell 3.5.4
  fi
}

function load-nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvm use default 1>/dev/null 2>&1
}

function load-travis() {
  [ -f "$HOME"/.travis/travis.sh ] && source "$HOME"/.travis/travis.sh
}

function load-fzf() {
  [ -f ~/.fzf.bash ] && source "$HOME"/.fzf.bash
}

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export NVM_DIR="$HOME/.nvm"
export LLVM_PATH=/usr/local/opt/llvm/bin
export PYTHON_CONFIGURE_OPTS="--enable-framework"
export PATH="/usr/local/bin:$LLVM_PATH:$HOME/.rvm/bin:$PATH"

load-python

# Custom parameters
export true=0
export false=1
export DOTFILES_PATH="$HOME"/Desktop/Projects/dotfiles
